# apiVersion: networking.k8s.io/v1beta1 # for k3s < v1.19
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: budgeto
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: budgeto-client-service
            port:
              number: 80
      - path: /server
        pathType: Prefix
        backend:
          service:
            name: budgeto-server-service
            port:
              number: 4000